# PNOZMulti Software V2.1dev
# Generic: Enabled the whole time
STO: 512 # robot is only allowed to move when the signal is 1
VERSION: 513 # version of modbus register specification, actual one is: 2

# Braketest: Disabled per default, can be enabled in robot.launch with parameter "has_braketest_support"
BRAKETEST_REQUEST: 514 # 0 = Test not required, 1 = Test required

# Operation mode: Disabled per default, can be enabled in robot.launch with parameter "has_operation_mode_support"
OPERATION_MODE: 515 # 0 = No Operation mode, 1 = T1, 2T2, 3 = Automatik, Operation modes according to EN ISO 10218
